### ISSUE TITLE
Merge data headers need to update if the delimiter headers change

### ISSUE THREAD

**Issue by sebastiz** [nhs-r-community/shinyEndomineR#22] opened 2021-12-14 13:12 UTC
The user may change the delimiters they want to use but at the moment the drop down feature (that lists all the fields that might be merged on) doesn't update with new delimiters

**Comment by ChrisBeeley** [comment] 2022-03-14 13:59
Duplicate of #22

**Closed by ChrisBeeley** 2022-03-14 13:59 UTC
